FROM krccl/mpich_base:332

RUN apt-get -y update &&  apt-get install -y libatlas-base-dev gfortran
RUN mkdir /hpl
WORKDIR /hpl
RUN curl -o hpl-2.3.tar.gz -L http://www.netlib.org/benchmark/hpl/hpl-2.3.tar.gz 
RUN tar xvf hpl-2.3.tar.gz -C /hpl --strip-component=1
ADD ./Make.ubuntu /hpl
RUN make arch=ubuntu
WORKDIR /hpl


